### ISSUE TITLE
Is sp explanation still needed?

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/VectorRaster#3]
Recent versions of `raster` can read (though not write) `sf` objects. So it might be a good idea to just explain how to convert between `sp` and `sf`, rather than explaining `sp` as well. Hopefully eventually we can just forget about `sp` altogether...

**Comment by janverbesselt** [comment]
indeed - let's do that for 2020.

**Comment by GreatEmerald** [comment]
So far there doesn't appear to be any reason to keep the sp explanation as that just confuses students. We should just say that if you have a Spatial object, you can get an sf object with `st_as_sf()`.

**Comment by GreatEmerald** [comment]
Solved.
